import React from 'react'
import Link from '../Link'

import preview_image from './assets/chain_animate.gif'

export default (
  <div>
    <p>
      <Link href="https://github.com/khiner/GeoLDMViz">GeoLDMViz</Link> is an interactive 3D visualizer for molecule
      chains generated by Geometric Latent Diffusion.
    </p>

    <img
      style={{ width: '75%' }}
      src={preview_image}
      alt="Animation showing a chain of molecules generated by Geometric Latent Diffusion"
    />
    <p style={{ textAlign: 'center' }}>
      <i>
        <Link href="https://www.youtube.com/watch?v=W7b-lYCAOLQ">Here is a short video</Link> showing vizualizer
        interaction.
      </i>
    </p>
    <p>
      <Link href="https://arxiv.org/pdf/2305.01140">GeoLDM</Link> (May 2023) was the first published effort to apply the
      Stable Diffusion paradigm of image generation to molecule generation. It uses variational autoencoders (VAEs) to
      encode the atomic coordinates and features (e.g. atomic types and charges) of a molecule into a continuous latent
      space, and decodes these latent codes back into the molecule data domain. Both the encoder and decoder are both
      parameterized with <Link href="https://arxiv.org/abs/2102.09844">Equivarient Graph Neural Networks</Link> (EGNNs)
      to enforce rotational and translational equivariance in 3D space (the learned likelihoods are SE(3)-invariant,
      where SE(3) is the Special Euclidean group of rotation and translation in 3D space).
    </p>
    <p>
      The visualizer application is agnostic to these model details. It simply loads any folder of{' '}
      <Link href="https://en.wikipedia.org/wiki/Chemical_file_format#XYZ">XYZ files</Link> and animates the contained
      molecule atomic types and coordinates. I generated the molecule chain animated above by dowloading GeoLDM's
      published{' '}
      <Link href="https://drive.google.com/drive/folders/1EQ9koVx-GA98kaKBS8MZ_jJ8g4YhdKsL?usp=sharing">
        pretrained models
      </Link>{' '}
      and sampling from the model trained on the <Link href="http://quantum-machine.org/datasets/">QM9 dataset</Link>.
      (I had to make small modifications to the model code to run inference on my Mac using MPS - details are in{' '}
      <Link href="https://github.com/khiner/GeoLDM/blob/mps/RunMps.md">my fork</Link>).
    </p>
    <p>
      Molecules are rendered using OpenGL 3, embedded in a docked ImGui window. It uses a simple{' '}
      <Link href="https://github.com/khiner/GeoLDMViz/blob/main/res/shaders/fragment.glsl">Phong shading model</Link>,
      with instanced spheres and cylinders for atoms and bonds. Bond presence is determined by{' '}
      <Link href="https://github.com/khiner/GeoLDMViz/blob/main/src/DatasetConfig.h">pairwise distance thresholds</Link>{' '}
      between atoms.
    </p>
  </div>
)
